version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: plango
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql    # 데이터 저장 볼륨
            - /home/ubuntu/mysql-init:/docker-entrypoint-initdb.d    # 초기화 스크립트
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: redis-container
        ports:
            - "6379:6379"
        networks:
            - app-network

    springboot-app:
        image: teniuscom/plango-backend:latest
        container_name: springboot-container
        ports:
            - "8080:8080"
        environment:
            SPRING_CONFIG_LOCATION: file:/app/config/application.properties
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/plango
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
        depends_on:
            - mysql
            - redis
        volumes:    # 로컬 디렉터리를 컨테이너 내부에 마운트
            # 파일 저장소
            - /home/ubuntu/storage:/home/ubuntu/storage
            # application.properties 파일을 외부에서 주입
            - /home/ubuntu/plango/application.properties:/app/config/application.properties
        networks:
            - app-network

volumes:
    mysql_data:  # 이름 있는 볼륨 (/var/lib/docker/volumes/ 하위에 저장)

networks:
    app-network:
